apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow        # Added namespace here
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
      nodePort: 30007

